---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes

  pre_tasks:
    - name: Update Apt Cache
      apt: update_cache=yes cache_valid_time=86400
      when: ansible_os_family == "Debian"
    - name: Ubuntu Packages
      apt: >
        pkg={{item}}
        state=present
      with_items:
        - jq
        - tree
        - sysstat
    - name: Stop systemd Resolver
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no
    - name: Removing bad resolver
      lineinfile: 
        path: /etc/resolv.conf
        regexp: 'nameserver\s+127\.0\.0\.53'
        state: absent
    - name: Adding known good resolver
      lineinfile: 
        path: /etc/resolv.conf
        regexp: '^nameserver\s+1.1.1.1'
        line: 'nameserver 1.1.1.1'
        state: present

    - name: create re home dir
      file:
        state: directory
        path: "/redis"
    - name: create ephemeral filesystem
      filesystem:
        fstype: ext4
        dev: "/dev/xvdh"
    - name: mount ephemeral dir filesystem
      mount:
        name: /redis/ephemeral
        src: /dev/xvdh
        fstype: ext4
        state: mounted
    - name: create persistant filesystem
      filesystem:
        fstype: ext4
        dev: "/dev/xvdj"
    - name: mount persistant dir filesystem
      mount:
        name: /redis/persistant
        src: /dev/xvdj
        fstype: ext4
        state: mounted

  tasks:
    - name: create download directory
      file:
        state: directory
        path: "/var/tmp/re-download"
        #    - name: download RE software
        #      get_url:
        #        url: https://s3.amazonaws.com/redis-enterprise-software-downloads/5.4.2/redislabs-5.4.2-20-bionic-amd64.tar
        #        dest: /var/tmp/re-download/redislabs-5.4.2-20-bionic-amd64.tar
    - name: Unarchive software
      unarchive: 
        src: "https://s3.amazonaws.com/redis-enterprise-software-downloads/5.4.2/redislabs-5.4.2-20-bionic-amd64.tar"
        dest: /var/tmp/re-download
        remote_src: yes
