---

- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes


  pre_tasks:
    - name: Load vars
      include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_hostname }}.yaml"
        - "default.yaml"

    - name: Update Apt Cache
      apt: 
        update_cache: yes
    - name: Ubuntu Packages
      package:
        name: "{{ deb_packages }}"
    - name: Stop systemd Resolver
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no
    - name: Removing bad resolver
      lineinfile: 
        path: /etc/resolv.conf
        regexp: 'nameserver\s+127\.0\.0\.53'
        state: absent
    - name: Adding known good resolver
      lineinfile: 
        path: /etc/resolv.conf
        regexp: '^nameserver\s+1.1.1.1'
        line: 'nameserver 1.1.1.1'
        state: present

    - name: create re home dir
      file:
        state: directory
        path: "/redis"
    - name: create ephemeral filesystem
      filesystem:
        fstype: ext4
        dev: "/dev/xvdh"
      when: enable_volumes
    - name: mount ephemeral dir filesystem
      mount:
        name: /redis/tmp
        src: /dev/xvdh
        fstype: ext4
        state: mounted
      when: enable_volumes
    - name: create persistant filesystem
      filesystem:
        fstype: ext4
        dev: "/dev/xvdj"
      when: enable_volumes
    - name: mount persistant dir filesystem
      mount:
        name: /redis/persist
        src: /dev/xvdj
        fstype: ext4
        state: mounted
      when: enable_volumes
    - name: create flash filesystem
      filesystem:
        fstype: ext4
        dev: "/dev/xvdi"
      when: enable_flash
    - name: mount flash dir filesystem
      mount:
        name: /redis/flash
        src: /dev/xvdi
        fstype: ext4
        state: mounted
      when: enable_flash

  tasks:
    - name: create download directory
      file:
        state: directory
        path: "/var/tmp/re-download"
    - name: Unarchive software
      unarchive: 
        src: /Users/jasonhaugland/Downloads/redislabs-6.2.12-68-bionic-amd64.tar
        dest: /var/tmp/re-download
    - name: Install the software
      command: "./install.sh -y"
      args:
        chdir: /var/tmp/re-download
        creates: /var/opt/redislabs/log/rlcheck.log
    - name: chown redis dir filesystem
      file:
       dest: /redis
       owner: redislabs
       group: redislabs
       recurse: yes
